
public enum PopUpType 
{
    Notification        = 0,
    NoEnergy            = 1,
    RecomendedUpdate    = 2,
    ForceUpdate         = 3,
    NoInternet          = 4,
    MainMenu            = 5,
    Shop                = 6,
    MegaSale            = 7,
    BuildPopUp          = 8,
    Map                 = 9,
    GetReward           = 10,
    GetChest            = 11,
    AttackPopUp         = 12,
    StealPopUp          = 13,
    NoCoins             = 14,
    Slot                = 15,
    Review              = 16,
    InAppReview         = 17,
    Settings            = 18,
    CardSets            = 19,
    CardSet             = 20,
    Card                = 21,
    BuildingPopUp       = 22,
    ComleteLevel        = 23,
    Credits             = 24,
    FindDiffMiniGame    = 25,
    License             = 26,
    PipeGame            = 27,
    HelpCatMiniGame     = 28,
    NoAdsDiscount       = 29,
    CrazyDiscount       = 30,
    PixelQuiz           = 31,
}
